<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <RootNamespace>PowerManager.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsPackageType Condition="'$(WindowsPackageType)' == ''">None</WindowsPackageType>
    <WindowsAppSDKSelfContained Condition="'$(WindowsPackageType)' == 'None'">true</WindowsAppSDKSelfContained>
    <ApplicationIcon>Assets\PowerManager.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.8249" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PowerManager.Core\PowerManager.Core.csproj" />
  </ItemGroup>
</Project>
